version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run: echo "Checked out the project"
      - run: gradle run
      - run: gradle test
      - run: echo "Build Complete"